"""Implement Beer Model

Revision ID: b3e7219a0c60
Revises:
Create Date: 2026-05-19 11:33:47.371970

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3e7219a0c60"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "beers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("alcohol_percentage", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("is_filtered", sa.Boolean(), nullable=False),
        sa.Column("beer_type", sa.Enum("DARK", "LIGHT", name="beertypeenum"), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.Column("total_amount", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_beers_id"), "beers", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_beers_id"), table_name="beers")
    op.drop_table("beers")
    # ### end Alembic commands ###
