"""Added amount >= 0 validation Beer Model

Revision ID: c95d8d8dd597
Revises: b3e7219a0c60
Create Date: 2026-05-20 13:00:16.222008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c95d8d8dd597'
down_revision: Union[str, Sequence[str], None] = 'b3e7219a0c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
