"""Added event type to beer model and intermediate table

Revision ID: eb231452a9e2
Revises: 6b8929476bb8
Create Date: 2026-06-15 22:25:01.758558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb231452a9e2'
down_revision: Union[str, Sequence[str], None] = '6b8929476bb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beer_event_types',
    sa.Column('beer_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('AFTER_WORK', 'WEEKEND_ESCAPE', 'FRIENDS_OVER', 'AFTER_MIDNIGHT', 'DINNER_AND_DRINKS', name='eventtypeenum'), nullable=False),
    sa.ForeignKeyConstraint(['beer_id'], ['beers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('beer_id', 'event_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beer_event_types')
    # ### end Alembic commands ###
